### ISSUE TITLE
how i can use it in redmine

### ISSUE THREAD

**Issue by ashrafalzyoud** [combit/RedmineReports#1]

**Comment by jbartlau** [comment]
@ashrafalzyoud Did you check the readme.md? Usually, you just need to start the exe and provide credentials for your redmine installation. This tool is a stand alone reporting tool and is not integrated into redmine but rather the other way around.

**Comment by ashrafalzyoud** [comment]
![33](https://user-images.githubusercontent.com/50211455/197630713-6384e03d-26b9-47ae-8684-8c42d91c6271.png)
not find mysql host
@jbartlau 
@DanielKenner

**Comment by jbartlau** [comment]
@ashrafalzyoud Can you make sure that remote access to your server is allowed by the MySql server policy? See [this article](https://www.digitalocean.com/community/tutorials/how-to-allow-remote-access-to-mysql) for hint on the configuration. Can you check your firewall and make sure the port is not blocked?

**Comment by ashrafalzyoud** [comment]
![2222](https://user-images.githubusercontent.com/50211455/198144666-d05c62f7-2c76-49c0-bcaa-2bab255c8de4.png)
im change the ip
give me another error
the host cant connect the mysqlserver

**Comment by jbartlau** [comment]
Just consult the arcticle linked above - this seems to be a MySQL configuration issue.
