### ISSUE TITLE
2 security vendors flagged this release as malicious

### ISSUE THREAD

**Issue by johnjeffersoncm** [combit/RedmineReports#2]
MaxSecure
Trojan.Malware.300983.susgen
Rising
Trojan.Generic@AI.90 (RDML:oyxeFMG9Y+P

https://www.virustotal.com/gui/file/ff0b64a5163fd19ab1b20855ed0d4c766a252bfddfb9bbf3eb8d560217302a2a?nocache=1

**Comment by jbartlau** [comment]
This is almost certainly a false positive. We'll check this with the vendors.

**Comment by jbartlau** [comment]
Both vendors are quite unresponsive, unfortunately, This seems to be a [common issue](https://github.com/Maximus5/ConEmu/issues/1214). Rising has officially deprecated services in 2013 ([Source](http://www.rising-global.com/)). We used their false positive reporting form anyway, but didn't get any answer. 

To sum up, we will not be able to flag these as false positives. As the vast majority of anti virus tools seems to be happy with the release as-is and we haven't uploaded new code for a while I'd use it happily if I was you. There's nothing more we can do on our end, unfortunately, to help ease your mind.
