### ISSUE TITLE
Security issues detected (Trojan)

### ISSUE THREAD

**Issue by johnjeffersoncm** [combit/RedmineReports#3]
Rising
Trojan.Generic@AI.96 (RDML:44sxC2ANgw
https://www.virustotal.com/gui/file/1d44e00d9e5385661533d1ef2b1360b0703217d79a3a73e5b67f7d07a209562f?nocache=1

Cynet
Malicious (score: 100)
https://www.virustotal.com/gui/file/897d7a4c17dc31d14b7fdd64e28fad3dae40a1df3540ec4c87708ec556637f2a?nocache=1

**Comment by johnjeffersoncm** [comment]
Please disregard. I saw now that I had already posted this:
https://github.com/combit/RedmineReports/issues/2

**Comment by jbartlau** [comment]
Thanks, thought I had heard that before 👍.
